version: 2

jobs:
  # Build & Deploy against development backend
  "build-dev":
    docker:
      - image: cimg/python:3.11.0-browsers
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: |
            sudo apt update
            sudo apt install jq
            sudo apt install python3-pip
            sudo pip3 install awscli --upgrade
            sudo pip3 install docker-compose

      - run:
          name: Executing build.
          command: |
            chmod +x build.sh
            ./build.sh DEV
      - deploy:
          name : Running Masterscript
          command: |
            git clone --branch v1.4.15 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .
            ./awsconfiguration.sh DEV
            source awsenvconf 
            ./buildenv.sh -e DEV -b legacy-member-processor_deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e DEV -t latest -s dev-global-appvar,dev-legacy-member-processor_appvar -i legacy-member-processor
              
  "build-prod":
    docker:
      - image: cimg/python:3.11.0-browsers
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: |
            sudo apt update
            sudo apt install jq
            sudo apt install python3-pip
            sudo pip3 install awscli --upgrade
            sudo pip3 install docker-compose

      - run:
          name: Executing build .
          command: |
             chmod +x build.sh
             ./build.sh PROD
      - deploy:
          name : Running Masterscript
          command: |
          
            git clone --branch v1.4.15 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .
            ./awsconfiguration.sh PROD
            source awsenvconf 
            ./buildenv.sh -e PROD -b legacy-member-processor_deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e PROD -t latest -s prod-global-appvar,prod-legacy-member-processor_appvar -i legacy-member-processor
        
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only: [ "develop", "dev-circleci" ]
      - "build-prod":
          context : org-global
          filters:
            branches:
              only: master
